### ISSUE TITLE
Allow catch all permissions

### ISSUE THREAD

**Issue by joaomilho** [klarna/kastlex#38]
Nowadays we have to add topic permissions to a user one by one. It would be nice to be able to do something like:

```yml
  user:
    produce:
      - us-staging.some-project.*
    fetch:
      - us-staging.some-project.*
```

or even:

```yml
  user:
   all:
      - us-staging.some-project.*
```
